/* Edit this file to update portfolio copy, links, and project metadata. */
window.PORTFOLIO = {
  brand: { name: "YASAR", descriptor: "SOFTWARE SYSTEMS ENGINEERING", short: "YSSE" },
  contact: { github: "https://github.com/Yasar101", email: "mailto:yasarashraf@outlook.com" },
  projects: [
    { name: "CLI Calculator", category: "Software development", type: "CLI_DEMO", tech: "Python · Decimal", status: "Tested", repo: "https://github.com/Yasar101/software-engineering-portfolio", focus: "Safe arithmetic parsing and explicit validation", limitation: "Command-line demonstration only.", command: "python3 demo.py calculator \"12.5 * 4\"" },
    { name: "Expense Tracker", category: "Software development", type: "LOCAL_INTERACTIVE", tech: "Python · JSON", status: "Tested core", repo: "https://github.com/Yasar101/software-engineering-portfolio", focus: "Expense models, totals and inspectable local persistence", limitation: "Persistent local CLI; no browser interface.", command: "python3 -m projects.expense_tracker --file expenses.json list" },
    { name: "Task Manager", category: "Software development", type: "LOCAL_INTERACTIVE", tech: "Python · SQLite", status: "Tested core", repo: "https://github.com/Yasar101/software-engineering-portfolio", focus: "Task lifecycle, filtering and local SQLite repository", limitation: "Persistent local CLI; no browser interface.", command: "python3 -m projects.task_manager --database tasks.sqlite3 list --status open" },
    { name: "Energy Calculator Pro", category: "Software development", type: "LOCAL_INTERACTIVE", tech: "Python · Decimal", status: "Tested core", repo: "https://github.com/Yasar101/software-engineering-portfolio", focus: "Transparent energy estimates using exact decimal calculations", limitation: "Local calculation with supplied values, not a supplier integration.", command: "python3 -m projects.energy_calculator --watts 850 --hours 3.5 --days 30 --tariff 0.28" },
    { name: "Weather Dashboard", category: "Backend engineering", type: "API_DEMO", tech: "Python · HTTP adapter", status: "Tested core", repo: "https://github.com/Yasar101/software-engineering-portfolio", focus: "Provider-response validation separated from presentation", limitation: "Live command needs network; offline fixture demo is also supplied.", command: "python3 -m projects.weather_dashboard 51.5072 -0.1276" },
    { name: "PostgreSQL REST API", category: "Backend engineering", type: "API_DEMO", tech: "Python · REST · SQL", status: "Tested reference", repo: "https://github.com/Yasar101/software-engineering-portfolio", focus: "HTTP semantics, validation and replaceable repository boundary", limitation: "Uses an in-memory reference adapter; PostgreSQL is not connected.", command: "python3 demo.py api" },
    { name: "Real-Time Monitoring Dashboard", category: "Systems engineering", type: "ARCHITECTURE_DEMO", tech: "Python · bounded metrics", status: "Tested core", repo: "https://github.com/Yasar101/software-engineering-portfolio", focus: "Thread-safe bounded metric windows and health states", limitation: "Local CLI uses clearly labelled simulated telemetry; no live telemetry UI.", command: "python3 -m projects.monitoring_dashboard latency_ms 112 128 146 121 --threshold 130" },
    { name: "Microservices Commerce Platform", category: "Systems engineering", type: "ARCHITECTURE_DEMO", tech: "Python · workflows", status: "Tested core", repo: "https://github.com/Yasar101/software-engineering-portfolio", focus: "Inventory reservation and payment-failure compensation", limitation: "In-process fictional transaction; not deployed services.", command: "python3 -m projects.microservices_commerce --decline-payment" },
    { name: "AI Developer Assistant", category: "AI engineering", type: "ARCHITECTURE_DEMO", tech: "Python · retrieval boundary", status: "Tested core", repo: "https://github.com/Yasar101/software-engineering-portfolio", focus: "Context retrieval, provider abstraction and credential rejection", limitation: "Uses a local deterministic provider; no external model provider or API key.", command: "python3 -m projects.ai_developer_assistant \"Where is token refresh handled?\"" },
    { name: "Distributed AI Platform", category: "Software architecture", type: "ARCHITECTURE_DEMO", tech: "Python · leases · retries", status: "Tested core", repo: "https://github.com/Yasar101/software-engineering-portfolio", focus: "Worker ownership, expiring leases and bounded retries", limitation: "Deterministic in-process scheduler with simulated workers, not deployed infrastructure.", command: "python3 -m projects.distributed_ai_platform --fail" }
  ]
};
